MODEL:
  NAME: 'ViT-B-16'
  STRIDE_SIZE: [16, 16]
  MEMORY_MOMENTUM: 0.2
  ID_LOSS_WEIGHT: 0.25
  PCL_LOSS_WEIGHT: 1.0
  # SIE_CAMERA: True
  # SIE_COE : 1.0

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
 
DATALOADER:
  NUM_INSTANCE: 8
  NUM_WORKERS: 8

SOLVER:
  IMS_PER_BATCH: 256
  OPTIMIZER_NAME: "SGD"
  BASE_LR: 3.5e-4
  WARMUP_METHOD: 'linear'
  WARMUP_ITERS: 10
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 5.0e-4
  MAX_EPOCHS: 60
  CHECKPOINT_PERIOD: 60
  LOG_PERIOD: 50
  EVAL_PERIOD: 60
  ITERS: 200
  
  STEPS: [30, 50]
  GAMMA: 0.1
  
TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False

DATASETS:
  NAMES: ('market1501')
  ROOT_DIR: ('/home/ljc/datasets')
OUTPUT_DIR: '/home/ljc/works/PCL-CLIP-release/logs'